### ISSUE TITLE
Add compiled build

### ISSUE THREAD

**Issue by Keith94** [Mesinger/MW3FovChanger#1]
Hey, if the project is working, would you mind adding a build to the [releases](https://github.com/Mesinger/MW3FovChanger/releases)?

**Comment by mesinger** [comment]
Sure!
Will do that asap.
thx for the issue

**Comment by Keith94** [comment]
Hi @Mesinger 
The build says some DLLs are not found. Could it be compiled in **debug** mode rather than **release** mode?

**Comment by mesinger** [comment]
thats indeed an issue

**Comment by mesinger** [comment]
I'll ask a friend with 10+ experience in C++ and .net to release a working build asap

**Comment by mesinger** [comment]
Alright, i think i figured it out.
The problem was, that i didn't staticly link all those microsoft, visual c++, .net, etc. librarys, which are missing on your machine.
i run the build on a completely fresh windows, without any preinstalled librarys, and it works now. will test it later this evening in mw3 and release it today.

thx for your issue

**Comment by mesinger** [comment]
I hope this works now.

**Comment by Keith94** [comment]
I'm afraid to say the .exe just opens a blank command prompt window for me. :(

**Comment by mesinger** [comment]
it wont do anything till you start either iw5sp.exe ir iw5mp.exe. if you do that it will beep and set the fov to 90

**Comment by Keith94** [comment]
Ok i see now. Thanks for the fix.
